CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	password VARCHAR(100) NOT NULL,
	location VARCHAR(4000) NOT NULL
);

CREATE TABLE categories (
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(4000) NOT NULL,
	description VARCHAR(4000) NOT NULL
);

CREATE TABLE products (
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(4000) NOT NULL,
	description VARCHAR(4000) NOT NULL,
	price FLOAT NOT NULL,
	category_id INT NOT NULL REFERENCES categories(id),
	user_id INT NOT NULL REFERENCES users(id),
	location VARCHAR(4000) NOT NULL,
	shippable INT NOT NULL
);

CREATE TABLE images (
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	product_id INT NOT NULL REFERENCES products(id),
	url VARCHAR(4000) NOT NULL
);

